# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 882e5698599d30f686323684ac4ad19c3a23c4d013da3f9c0210c56b83d917d0b7d5f40148f8af66378d281d7995a6a106d7e0561ad8d11508fadc9495ffa91c

test:
  secret_key_base: 25e6a34239d7959f9105eecf7af3d8064d96bb876ddf33fc61820aac1678e37bfb95e7db23a02e430100c5ae3a5548ee43fb41869c4af2c610b2309f6a878255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
